language: ruby

addons:
  postgresql: 9.4
  code_climate:
    secure: 4Ihi7AN4Fje6MUCHYb9ei8rB8eYTKI2jl9LW8SN48+xyZ2g69Dcn4TJZ6bnlOuTRv6A3c2p6iiiLcR/oJN67loFBKTO3+DtSkhuCiISEFzUXihgRYGUMi9bOpSuCa2i6rTfrThgTUrnqku3KiEL8lOCDs1NV/kscmZtursXm1xBl3GP+L3mBDaDTZ1/wQAOKS7XXNc7rJsD8dSlR5hmErYewdNobnZI7Y4vXD0s6anHw2BoeS/pVmgyjCrJSLW/lW5vca2WQ9cjinHsu1p/kI+qzNvDFpM2gevaGZjaLcN8ccZ+TTPJhzpuatLKBLgZI+kBH81ujY9kTi8Lv2kKqGfCRdulAjhQyNAEnKwiqQLpQyKuQXQ34MDMALCu3IjvEX/+GKvgiFbZBYFpOF7Hze5vBTGl2tefcb3fXaHmlzEH5Uru90xZqVuqbGPnc0G4kjbMBLRz0RSKkauJRL80+KX0lm/alnCSDzFjHrmy319CdWbLifG7BAs0RsXFafet/BP+X3y4bl+Cl8Pblm8LTnCiNs8N70DeGA/PhLBavv2XoEnEsxhYPatwJdNHlLTRUUQc/RIoJwxMnNh/I3IMvIsxEzSf30mR/Q3IaM1xKdbficxGt/ewtp80XdbLDIpIMcUjm+NQqH1S8MixRKazl3BQv5+CX29hJDagwRuXx8nQ=

rvm:
  - 2.2.4
  - 2.3.0

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000

services:
  - redis

sudo: false

cache: bundler

before_script:
  - cp config/database.yml.ci config/database.yml
  - cp config/exsules.yml.example config/exsules.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace

bundler_args: "--without development --jobs 3 --retry 5"

script:
  - RAILS_ENV=test CODECLIMATE=true bundle exec rspec

notifications:
  email: false
  slack:
    rooms:
      secure: S/aOGrs+HR2z9bKVPGZWWFRuPVulFWJKpU/F/rKtXAIiQ7Co0LP88DH74VxWtlnREU36XRCL+rL8++BYw6VprDXK25d1q9BAIwuQudVtbEYmgs4VohsjMUUhW9OIZhb+3sCcvRp4xC1A/MY0CGGugcS8shPAQCDIwWna524XNSgrnbXb9NyrVklI675CiaOMe6IhOxDzqeR81a/7fmOsXDq6QQuhuEGh9WVW0tB5Cn+JQxXQxfujmcH6FNA1TOTXywNdhC3XNTiJlnDBHyeVCuYlY2eeva7aL9IPsP1rnPrXVBLmRHohJae/GOrhumEwmaNX5UuPpOmZyKwjuaI4c7N51n7r2BNcZ/9WWpNmq8JI5wiL2mDWxFdqb+d3efCJlj+USawb7mo+mpXsW86sr6aGuibv5RlgHxxXURxnhAUJnJ3EVWnVt4hnrW07tuU36lpr0VqtpG3IF2Be8gA45PSw4eBEHlq1NzberBshWA/QrS849aakeJR35es+Jgwt6CiDFekd5sYvsbCnPbwGTqEaWkycI5+Qvf+vZZtMZrWrjh70XX0WUeB3LXml3QOOG7en5BxCLL7W2cc1RKkhQqfLXKHAvvUiK9rKritRTUIyXVNsUNVot7jkoT20z0jAKrNpnrl62l/8ro3Qr5pxRgvSozRTvGbTwBne+bjlUBg=
